name: CD - Commands Package

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Cli.Commands/Cli.Commands.csproj'
      - '.github/workflows/cd-commands-package.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PROJECT_FILE: ./src/Cli.Commands/Cli.Commands.csproj

    steps:

    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore $PROJECT_FILE

    - name: Build
      run: dotnet build $PROJECT_FILE --no-restore -c Release

    - name: Pack Commands
      run: dotnet pack $PROJECT_FILE -c Release

    - name: Push Commands Package
      run: dotnet nuget push src/Cli.Commands/bin/**/*.nupkg --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source https://api.nuget.org/v3/index.json
