name: CI - Source

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - '.github/workflows/ci-source.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE: src/Structurizr.Tools.sln

    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Restore dependencies
      run: dotnet restore $SOLUTION_FILE

    - name: Build
      run: dotnet build $SOLUTION_FILE --no-restore
      
    - name: Test
      run: dotnet test $SOLUTION_FILE --no-build --verbosity normal